/* Generated by Gemini 3 */
#pragma once
#include <cmath>
#include <functional>
#include <utility>

namespace pp {

struct IntResult {
    double value;
    double error;
};

// 1. Recursive open 4-point adaptive integrator
template<typename F>
IntResult integrate(F f, double a, double b, double acc = 0.001, double eps = 0.001, 
                    double f2 = NAN, double f3 = NAN) {
    double h = b - a;
    
    if (std::isnan(f2)) { // first call
        f2 = f(a + 2.0 * h / 6.0);
        f3 = f(a + 4.0 * h / 6.0);
    }
    
    double f1 = f(a + 1.0 * h / 6.0);
    double f4 = f(a + 5.0 * h / 6.0);

    double Q = (2.0 * f1 + f2 + f3 + 2.0 * f4) / 6.0 * h; // higher order rule
    double q = (f1 + f2 + f3 + f4) / 4.0 * h;             // lower order rule

    double err = std::abs(Q - q);
    double tol = acc + eps * std::abs(Q);

    if (err < tol) {
        return {Q, err};
    } else {
        IntResult res1 = integrate(f, a, a + h / 2.0, acc / std::sqrt(2.0), eps, f1, f2);
        IntResult res2 = integrate(f, a + h / 2.0, b, acc / std::sqrt(2.0), eps, f3, f4);
        return {res1.value + res2.value, std::sqrt(res1.error * res1.error + res2.error * res2.error)};
    }
}

// 2. Clenshaw-Curtis variable transformation integrator
template<typename F>
IntResult integrate_cc(F f, double a, double b, double acc = 0.001, double eps = 0.001) {
    auto f_cc = [&](double theta) {
        return f((a + b) / 2.0 + (b - a) / 2.0 * std::cos(theta)) * std::sin(theta) * (b - a) / 2.0;
    };
    // The transformation maps [a, b] to [0, pi]
    return integrate(f_cc, 0.0, M_PI, acc, eps);
}

// 3. Infinite limit wrapper for [a, infinity)
template<typename F>
IntResult integrate_inf(F f, double a, double acc = 0.001, double eps = 0.001) {
    auto f_inf = [&](double t) {
        return f(a + (1.0 - t) / t) / (t * t);
    };
    // Maps [a, infinity) to [0, 1], then apply CC integrator
    return integrate_cc(f_inf, 0.0, 1.0, acc, eps);
}

// 4. Infinite limit wrapper for (-infinity, infinity)
template<typename F>
IntResult integrate_inf_inf(F f, double acc = 0.001, double eps = 0.001) {
    auto f_inf_inf = [&](double t) {
        double x = t / (1.0 - t * t);
        double dx_dt = (1.0 + t * t) / ((1.0 - t * t) * (1.0 - t * t));
        return f(x) * dx_dt;
    };
    // Maps (-infinity, infinity) to (-1, 1), then apply CC integrator
    return integrate_cc(f_inf_inf, -1.0, 1.0, acc, eps);
}

} // namespace pp
