/* Generated by Gemini 3 */
#include "matrix.h"
#include "qr.h"
#include <iostream>
#include <cstdio>
#include <cassert>
#include <cmath>
#include <string>
#include <vector>
#include <functional>
#include <stdexcept>

// Redefining macros here to ensure the .cc file can use them
#define SELF (*this)
#define FOR(i,V) for(int i=0; i<(int)V.size(); i++)
#define FOR1(i,A) for(int i=0; i<(int)A.size1(); i++)
#define FOR2(j,A) for(int j=0; j<(int)A.size2(); j++)

namespace pp {

// --- Vector Implementation ---

vector& vector::operator+=(const vector& other) {
    FOR(i, SELF) SELF[i] += other[i];
    return SELF;
}

vector& vector::operator-=(const vector& other) {
    FOR(i, SELF) SELF[i] -= other[i];
    return SELF;
}

vector& vector::operator*=(double c) {
    FOR(i, SELF) SELF[i] *= c;
    return SELF;
}

vector& vector::operator/=(double c) {
    FOR(i, SELF) SELF[i] /= c;
    return SELF;
}

double vector::norm() const {
    double sum2 = 0;
    FOR(i, SELF) sum2 += SELF[i] * SELF[i];
    return std::sqrt(sum2);
}

void vector::print(std::string s) const {
    std::cout << s;
    for (auto &x : data) printf("%10.3g ", x);
    std::cout << "\n";
}

vector vector::map(std::function<double(double)> f) const {
    vector r(size());
    FOR(i, SELF) r.data[i] = f(data[i]);
    return r;
}

// Global operators for vectors
vector operator+(vector a, const vector& b) { a += b; return a; }
vector operator-(vector a) { a *= -1.0; return a; }
vector operator-(vector a, const vector& b) { a -= b; return a; }
vector operator*(vector a, double c) { a *= c; return a; }
vector operator*(double c, vector a) { a *= c; return a; }
vector operator/(vector a, double c) { a /= c; return a; }

bool approx(double x, double y, double acc, double eps) {
    if (std::abs(x - y) < acc) return true;
    if (std::abs(x - y) < eps * std::max(std::abs(x), std::abs(y))) return true;
    return false;
}

bool approx(const vector& a, const vector& b, double acc, double eps) {
    if (a.size() != b.size()) return false;
    for (int i = 0; i < a.size(); i++)
        if (!approx(a[i], b[i], acc, eps)) return false;
    return true;
}

// --- Matrix Implementation ---

void matrix::setid() {
    assert(size1() == size2());
    for (int i = 0; i < size1(); i++) {
        for (int j = 0; j < size2(); j++) {
            SELF(i, j) = (i == j ? 1.0 : 0.0);
        }
    }
}

matrix matrix::transpose() const {
    matrix R(size2(), size1());
    FOR1(i, SELF) {
        FOR2(j, SELF) {
            R(j, i) = SELF(i, j);
        }
    }
    return R;
}

matrix& matrix::operator+=(const matrix& B) {
    for (int i = 0; i < size2(); i++) SELF[i] += B[i];
    return *this;
}

matrix& matrix::operator-=(const matrix& B) {
    for (int i = 0; i < size2(); i++) SELF[i] -= B[i];
    return *this;
}

matrix& matrix::operator*=(double c) {
    for (int i = 0; i < size2(); i++) SELF[i] *= c;
    return *this;
}

matrix& matrix::operator/=(double c) {
    for (int i = 0; i < size2(); i++) SELF[i] /= c;
    return *this;
}

void matrix::print(std::string s) const {
    printf("%s\n", s.c_str());
    for (int i = 0; i < size1(); i++) {
        for (int j = 0; j < size2(); j++) {
            printf("%10.3g ", SELF(i, j));
        }
        printf("\n");
    }
}

bool approx(const matrix& A, const matrix& B, double acc, double eps) {
    if (A.size1() != B.size1() || A.size2() != B.size2()) return false;
    for (int j = 0; j < A.size2(); j++) {
        // Compare column j of A with column j of B
        if (!approx(A[j], B[j], acc, eps)) return false;
    }
    return true;
}

// Global operators for matrices
matrix operator+(matrix A, const matrix& B) { A += B; return A; }
matrix operator-(matrix A, const matrix& B) { A -= B; return A; }

matrix operator*(const matrix& A, const matrix& B) {
    if (A.size2() != B.size1()) throw std::invalid_argument("Matrix size mismatch");
    matrix R(A.size1(), B.size2());
    
    // Inicializar explícitamente a cero para evitar basura
    for(int j=0; j<R.size2(); j++) 
        for(int i=0; i<R.size1(); i++) R(i,j) = 0.0;

    for (int k = 0; k < A.size2(); k++) {
        for (int j = 0; j < B.size2(); j++) {
            double Bkj = B(k, j);
            for (int i = 0; i < A.size1(); i++) {
                R(i, j) += A(i, k) * Bkj;
            }
        }
    }
    return R;
}

matrix operator*(matrix A, double c) { A *= c; return A; }
matrix operator*(double c, matrix A) { A *= c; return A; }

// Fixed the return typo here (A instead of a)
matrix operator/(matrix A, double c) { A /= c; return A; }

vector operator*(const matrix& A, const vector& v) {
    if (A.size2() != v.size()) throw std::invalid_argument("Matrix-Vector size mismatch");
    vector r(A.size1());
    for(int i=0; i<r.size(); i++) r[i] = 0.0;
    FOR2(j, A) {
        double vj = v[j];
        FOR1(i, A) r[i] += A(i, j) * vj;
    }
    return r;
}

double qr::det() const {
    // Check if the matrix is square
    if (R.size1() != R.size2()) {
        std::cerr << "Error: Determinant only defined for square matrices.\n";
        return 0;
    }

    double d = 1.0;
    for (int i = 0; i < R.size1(); i++) {
        d *= R(i, i);
    }
    
    // Note: This returns det(R). Since det(A) = det(Q)*det(R) 
    // and for Gram-Schmidt QR, Q's determinant is usually 1 or -1,
    // this gives the magnitude. 
    return d;
}

matrix qr::inverse() const {
    int n = R.size1();
    int m = R.size2();
    if (n != m) {
        throw std::invalid_argument("Inverse only exists for square matrices.");
    }

    matrix Inv(n, n);
    matrix I(n, n);
    I.setid(); // Create an identity matrix to get the columns e_j

    for (int j = 0; j < n; j++) {
        // The j-th column of the inverse is the solution to A * x = e_j
        vector ej = I[j]; 
        vector xj = solve(ej);
        
        // Place the result xj into the j-th column of our Inverse matrix
        for (int i = 0; i < n; i++) {
            Inv(i, j) = xj[i];
        }
    }
    return Inv;
}



} // namespace pp
