/* Generated by Gemini 3 */
#pragma once
#include "matrix.h"
#include "minimize.h"
#include <cmath>
#include <vector>
#include <functional>

namespace pp {

struct ann {
    int n;
    std::function<double(double)> f;
    pp::vector p;

    ann(int num_neurons) : n(num_neurons), p(3 * num_neurons) {
        // Gaussian wavelet activation function: f(x) = x * exp(-x^2)
        f = [](double x) { return x * std::exp(-x * x); };

        // Optimized initial geometry to capture the shifted cos(5x - 1) phase
        for (int i = 0; i < n; i++) {
            // Distribute centers across the domain
            p[3 * i + 0] = -0.9 + 1.8 * i / (n > 1 ? n - 1 : 1); 
            
            // Start with slightly tighter widths so neurons can track the fast 5x frequency
            p[3 * i + 1] = 0.35;                                 
            
            // Alternating stronger initial weights to jumpstart the Newton step gradients
            p[3 * i + 2] = (i % 2 == 0) ? 1.5 : -1.5;            
        }
    }


    // --- Analytical Calculus for Gaussian Wavelet ---
    inline double df(double x) const { return (1.0 - 2.0 * x * x) * std::exp(-x * x); }
    inline double d2f(double x) const { return (4.0 * x * x * x - 6.0 * x) * std::exp(-x * x); }
    inline double f_anti(double x) const { return -0.5 * std::exp(-x * x); }

    // --- Network Outputs ---
    double response(double x) const {
        double sum = 0;
        for (int i = 0; i < n; i++) sum += p[3*i+2] * f((x - p[3*i+0]) / p[3*i+1]);
        return sum;
    }

    double derivative(double x) const {
        double sum = 0;
        for (int i = 0; i < n; i++) sum += (p[3*i+2] / p[3*i+1]) * df((x - p[3*i+0]) / p[3*i+1]);
        return sum;
    }

    double derivative2(double x) const {
        double sum = 0;
        for (int i = 0; i < n; i++) sum += (p[3*i+2] / (p[3*i+1] * p[3*i+1])) * d2f((x - p[3*i+0]) / p[3*i+1]);
        return sum;
    }

    double antiderivative(double x) const {
        double sum = 0;
        for (int i = 0; i < n; i++) sum += p[3*i+2] * p[3*i+1] * f_anti((x - p[3*i+0]) / p[3*i+1]);
        return sum;
    }

    // --- Training Methods ---
    void train(const pp::vector& x_data, const pp::vector& y_data) {
        auto cost_func = [&](pp::vector params) -> double {
            pp::vector p_old = p;
            p = params;
            double cost = 0;

            // 1. Standard Interpolation Error
            for (int k = 0; k < x_data.size(); k++) {
                double diff = response(x_data[k]) - y_data[k];
                cost += diff * diff;
            }

            // 2. Smooth Penalties (The "Walls" to keep Newton's method safe)
            for (int i = 0; i < n; i++) {
                /* double a = params[3 * i + 0];*/
                double b = params[3 * i + 1];
                double w = params[3 * i + 2];

                // Keep b away from zero! (Prevents F''(x) from exploding)
                if (std::abs(b) < 0.2) {
                    double dist = 0.2 - std::abs(b);
                    cost += 1000.0 * dist * dist;
                }
                // Keep weights from running away
                cost += 0.001 * (w * w);
            }

            p = p_old;
            return cost;
        };

        // Run your existing minimizer
        auto result = pp::newton_min(cost_func, p, 1e-4, true);
        p = result.first;
    }

    void train_ode(
        std::function<double(double, double, double, double)> phi,
        double a_interv, double b_interv,
        double c, double yc, double dyc,
        double alpha, double beta, int num_points = 25
    ) {
        auto cost_func = [&](pp::vector params) -> double {
            pp::vector p_old = p;
            p = params;
            double cost = 0;

            double dx = (b_interv - a_interv) / (num_points - 1);
            for (int i = 0; i < num_points; i++) {
                double x = a_interv + i * dx;
                double residual = phi(derivative2(x), derivative(x), response(x), x);
                cost += residual * residual * dx;
            }

            // Boundary conditions
            double bc1 = response(c) - yc;
            double bc2 = derivative(c) - dyc;
            cost += alpha * bc1 * bc1 + beta * bc2 * bc2;

            // Same safety penalty for ODE
            for (int i = 0; i < n; i++) {
                double b = params[3 * i + 1];
                if (std::abs(b) < 0.2) {
                    double dist = 0.2 - std::abs(b);
                    cost += 1000.0 * dist * dist;
                }
            }

            p = p_old;
            return cost;
        };

        auto result = pp::newton_min(cost_func, p, 1e-4, true);
        p = result.first;
    }
};

} // namespace pp
