/* Generated by Gemini 3 */
#pragma once
#include "matrix.h"
#include "qr.h"
#include <cmath>
#include <functional>
#include <utility>

namespace pp {

// --- Forward Difference Approximations (Part A) ---

inline pp::vector gradient_forward(std::function<double(pp::vector)> f, pp::vector x, double& fx) {
    fx = f(x);
    pp::vector g(x.size());
    for (int i = 0; i < x.size(); ++i) {
        double dx = (1.0 + std::abs(x[i])) * std::pow(2.0, -26); // eps^(1/2)
        x[i] += dx;
        g[i] = (f(x) - fx) / dx;
        x[i] -= dx;
    }
    return g;
}

inline pp::matrix hessian_forward(std::function<double(pp::vector)> f, pp::vector x) {
    pp::matrix H(x.size(), x.size());
    double fx;
    pp::vector gx = gradient_forward(f, x, fx);
    for (int j = 0; j < x.size(); ++j) {
        double dx = (1.0 + std::abs(x[j])) * std::pow(2.0, -13); // eps^(1/4)
        x[j] += dx;
        double dummy;
        pp::vector dg = gradient_forward(f, x, dummy) - gx;
        for (int i = 0; i < x.size(); ++i) {
            H(i, j) = dg[i] / dx;
        }
        x[j] -= dx;
    }
    return H;
}

// --- Central Difference Approximations (Part C) ---

// Evaluates the gradient and Hessian simultaneously to save redundant f(x) calls
inline std::pair<pp::vector, pp::matrix> grad_hess_central(std::function<double(pp::vector)> f, pp::vector x) {
    int n = x.size();
    pp::vector g(n);
    pp::matrix H(n, n);
    double fx = f(x);
    
    std::vector<double> dx(n);
    for (int i = 0; i < n; ++i) {
        dx[i] = (1.0 + std::abs(x[i])) * std::pow(2.0, -18); // eps^(1/3)
    }
    
    pp::vector x_tmp = x;
    
    // Gradient and diagonal Hessian elements (Shared evaluations)
    for (int i = 0; i < n; ++i) {
        x_tmp[i] = x[i] + dx[i]; double fp = f(x_tmp);
        x_tmp[i] = x[i] - dx[i]; double fm = f(x_tmp);
        x_tmp[i] = x[i]; // Restore
        
        g[i] = (fp - fm) / (2.0 * dx[i]);
        H(i, i) = (fp - 2.0 * fx + fm) / (dx[i] * dx[i]);
    }
    
    // Off-diagonal Hessian elements
    for (int i = 0; i < n; ++i) {
        for (int j = i + 1; j < n; ++j) {
            x_tmp[i] = x[i] + dx[i]; x_tmp[j] = x[j] + dx[j]; double fpp = f(x_tmp);
            x_tmp[i] = x[i] + dx[i]; x_tmp[j] = x[j] - dx[j]; double fpm = f(x_tmp);
            x_tmp[i] = x[i] - dx[i]; x_tmp[j] = x[j] + dx[j]; double fmp = f(x_tmp);
            x_tmp[i] = x[i] - dx[i]; x_tmp[j] = x[j] - dx[j]; double fmm = f(x_tmp);
            x_tmp[i] = x[i]; x_tmp[j] = x[j]; // Restore
            
            double d2f = (fpp - fpm - fmp + fmm) / (4.0 * dx[i] * dx[j]);
            H(i, j) = d2f;
            H(j, i) = d2f; // Symmetry
        }
    }
    return {g, H};
}

// --- Newton's Minimization Method ---

inline std::pair<pp::vector, int> newton_min(
    std::function<double(pp::vector)> f, 
    pp::vector x, 
    double acc = 1e-3, 
    bool use_central = false
) {
    int steps = 0;
    while (steps < 1000) { // Safety constraint
        steps++;
        pp::vector g;
        pp::matrix H(x.size(), x.size());
        
        if (use_central) {
            auto gh = grad_hess_central(f, x);
            g = gh.first;
            H = gh.second;
        } else {
            double dummy;
            g = gradient_forward(f, x, dummy);
            H = hessian_forward(f, x);
        }
        
        if (g.norm() < acc) break; // Job done
        
        // Levenberg regularization
        for (int i = 0; i < H.size1(); i++) H(i, i) += 1e-6; 
        
        pp::qr QR(H);
        pp::vector dx = QR.solve(-1.0 * g);
        
        double lambda = 1.0;
        double fx_val = f(x);
        
        // Backtracking line search
        while (lambda >= 1.0 / 1024.0) {
            if (f(x + dx * lambda) < fx_val) break; // Good step
            lambda /= 2.0;
        }
        x = x + dx * lambda;
    }
    return {x, steps};
}

} // namespace pp
