/* Generated by Gemini 3 */
#include <iostream>
#include <fstream>
#include <cmath>
#include <vector>
#include <functional>
#include "matrix.h"
#include "qr.h"
#include "lsfit.h"

int main() {
    // 1. Experimental Data (Rutherford and Soddy - ThX)
    pp::vector t = {1, 2, 3, 4, 6, 9, 10, 13, 15};
    pp::vector y_act = {117, 100, 88, 72, 53, 29.5, 25.2, 15.2, 11.1};
    pp::vector dy_act = {6, 5, 4, 4, 4, 3, 3, 2, 2};

    int n = t.size();
    pp::vector ln_y(n);
    pp::vector dln_y(n);

    // Write raw data to file for plotting
    std::ofstream data_file("data.txt");
    for (int i = 0; i < n; i++) {
        ln_y[i] = std::log(y_act[i]);
        dln_y[i] = dy_act[i] / y_act[i]; // The proven uncertainty
        data_file << t[i] << " " << y_act[i] << " " << dy_act[i] << "\n";
    }
    data_file.close();

    // 2. Define fitting functions: f0(t) = 1, f1(t) = t
    std::vector<std::function<double(double)>> fs = {
        [](double) { return 1.0; },
        [](double x) { return x; }
    };

    // 3. Perform Least Squares Fit
    auto [c, Sigma] = pp::lsfit(fs, t, ln_y, dln_y);

    double c0 = c[0];
    double c1 = c[1];
    double dc0 = std::sqrt(Sigma(0, 0));
    double dc1 = std::sqrt(Sigma(1, 1));

    // 4. Calculate Half-Life
    // Since ln(y) = ln(a) - lambda*t, our c1 is (-lambda)
    double lambda = -c1;
    double dlambda = dc1;

    double half_life = std::log(2.0) / lambda;
    // Error propagation for T_1/2: dT = |dT/dlambda| * dlambda = (ln(2)/lambda^2) * dlambda
    double d_half_life = (std::log(2.0) / (lambda * lambda)) * dlambda;

    // Modern value for 224Ra
    double modern_half_life = 3.6319; // days

    // Print Results
    std::cout << "--- Rutherford & Soddy ThX (224Ra) Decay Fit ---\n";
    std::cout << "Best fit c0 (ln(a)): " << c0 << " +/- " << dc0 << "\n";
    std::cout << "Best fit c1 (-lambda): " << c1 << " +/- " << dc1 << "\n";
    std::cout << "\nCalculated Half-Life: " << half_life << " +/- " << d_half_life << " days\n";
    std::cout << "Modern Half-Life (224Ra): " << modern_half_life << " days\n";

    if (std::abs(half_life - modern_half_life) <= d_half_life) {
        std::cout << "Conclusion: The modern value IS within our estimated uncertainty.\n";
    } else {
        std::cout << "Conclusion: The modern value is slightly outside our estimated uncertainty.\n";
    }

    // 5. Generate smooth curves for Gnuplot (including +/- uncertainty bounds)
    std::ofstream curve_file("fit_curves.txt");
    for (double t_plot = 0; t_plot <= 16; t_plot += 0.2) {
        double y_fit = std::exp(c0 + c1 * t_plot);

        // Worst-case combinations of uncertainties
        double y_up = std::exp((c0 + dc0) + (c1 + dc1) * t_plot);
        double y_down = std::exp((c0 - dc0) + (c1 - dc1) * t_plot);
        double y_up2 = std::exp((c0 + dc0) + (c1 - dc1) * t_plot);
        double y_down2 = std::exp((c0 - dc0) + (c1 + dc1) * t_plot);

        curve_file << t_plot << " " << y_fit << " "
                   << y_up << " " << y_down << " "
                   << y_up2 << " " << y_down2 << "\n";
    }
    curve_file.close();

    return 0;
}
