/* Generated by Gemini 3 */
#pragma once
#include "matrix.h"
#include "qr.h"
#include <cmath>
#include <functional>
#include <vector>

namespace pp {

// Approximates the Jacobian matrix using finite differences.
// Optimized to update an existing matrix in-place instead of reallocating.
inline void Jacobian(std::function<pp::vector(pp::vector)> f, pp::vector x, pp::vector fx, pp::matrix& J) {
    int n = x.size();
    for (int j = 0; j < n; ++j) {
        double dx = std::max(std::abs(x[j]), 1.0) * std::pow(2.0, -26);
        x[j] += dx;
        pp::vector df = f(x) - fx;
        for (int i = 0; i < n; ++i) {
            J(i, j) = df[i] / dx;
        }
        x[j] -= dx; // Restore original value
    }
}

// Newton's method with quadratic interpolation line search
inline pp::vector newton(
    std::function<pp::vector(pp::vector)> f,
    pp::vector x,
    double acc = 1e-3,
    double alpha_min = 1e-4,
    int max_iter = 1000
) {
    int n = x.size();
    pp::matrix J(n, n); // Allocated only once!
    pp::vector fx = f(x);
    
    for (int iter = 0; iter < max_iter; ++iter) {
        if (fx.norm() < acc) break;
        
        Jacobian(f, x, fx, J);
        pp::qr QRJ(J);
        pp::vector dx = QRJ.solve(-1.0 * fx); // Newton's step
        
        double alpha = 1.0;
        double phi_0 = 0.5 * std::pow(fx.norm(), 2);
        double dphi_0 = -2.0 * phi_0; // Approximation of derivative at alpha=0 [cite: 60]
        
        pp::vector z;
        pp::vector fz;
        
        while (true) {
            z = x + dx * alpha;
            fz = f(z);
            double phi_alpha = 0.5 * std::pow(fz.norm(), 2);
            
            // Armijo condition [cite: 44, 46]
            if (phi_alpha < (1.0 - alpha / 2.0) * phi_0) break; 
            if (alpha < alpha_min) break; // Accept the bad step to escape [cite: 46]
            
            // Quadratic interpolation [cite: 63, 64]
            double c = (phi_alpha - phi_0 - dphi_0 * alpha) / (alpha * alpha);
            double alpha_next = -dphi_0 / (2.0 * c); // [cite: 67]
            
            // Safeguard bounds for the interpolated step
            if (alpha_next > 0.1 * alpha && alpha_next < 0.9 * alpha) {
                alpha = alpha_next;
            } else {
                alpha /= 2.0; // Fallback to simple backtracking
            }
        }
        x = z;
        fx = fz;
    }
    return x;
}

} // namespace pp
