/* Generated by Gemini 3 */
#pragma once
#include <vector>
#include <cmath>
#include <utility>
#include <random>
#include <iostream>

namespace pp {

struct MCResult {
    double value;
    double error;
};

// --- Custom Linear Congruential Generator ---
class lcg {
    unsigned long long seed;
    unsigned long long a, c, m;
public:
    lcg(unsigned long long s = 42, unsigned long long a_ = 1664525,
        unsigned long long c_ = 1013904223, unsigned long long m_ = 4294967296ull) // 2^32
        : seed(s), a(a_), c(c_), m(m_) {}

    double operator()() {
        seed = (a * seed + c) % m;
        return static_cast<double>(seed + 1) / static_cast<double>(m + 1);
    }
};

// --- Plain Monte Carlo Integrator ---
template<typename F, typename RNG>
MCResult plainmc(F f, const std::vector<double>& a, const std::vector<double>& b, int N, RNG& random_double) {
    int dim = a.size();
    double V = 1.0;
    for (int i = 0; i < dim; ++i) V *= (b[i] - a[i]);

    double sum = 0.0, sum2 = 0.0;
    std::vector<double> x(dim);

    for (int i = 0; i < N; ++i) {
        for (int d = 0; d < dim; ++d) {
            x[d] = a[d] + random_double() * (b[d] - a[d]);
        }
        double fx = f(x);
        sum += fx;
        sum2 += fx * fx;
    }

    double mean = sum / N;
    double var = sum2 / N - mean * mean;
    if (var < 0) var = 0; // Catch floating point inaccuracies

    double sigma = std::sqrt(var);
    return {mean * V, sigma * V / std::sqrt(N)};
}

// --- Halton Sequence Generator (for Quasi-Random) ---
inline double corput(int n, int base) {
    double q = 0, bk = 1.0 / base;
    while (n > 0) {
        q += (n % base) * bk;
        n /= base;
        bk /= base;
    }
    return q;
}

inline void halton(int n, int dim, std::vector<double>& x) {
    int bases[] = {2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71};
    for (int i = 0; i < dim; ++i) {
        x[i] = corput(n, bases[i % 20]);
    }
}

// --- Quasi-Random Monte Carlo Integrator ---
template<typename F>
MCResult quasimc(F f, const std::vector<double>& a, const std::vector<double>& b, int N) {
    int dim = a.size();
    double V = 1.0;
    for (int i = 0; i < dim; ++i) V *= (b[i] - a[i]);

    double sum1 = 0.0, sum2 = 0.0;
    std::vector<double> x1(dim), x2(dim);

    for (int i = 1; i <= N / 2; ++i) {
        // Sequence 1: Standard Halton
        halton(i, dim, x1);
        // Sequence 2: Shifted Halton (offset to avoid correlation)
        halton(i + 50000, dim, x2);

        // Map to volume
        std::vector<double> p1(dim), p2(dim);
        for(int d=0; d<dim; d++){
            p1[d] = a[d] + x1[d] * (b[d] - a[d]);
            p2[d] = a[d] + x2[d] * (b[d] - a[d]);
        }

        sum1 += f(p1);
        sum2 += f(p2);
    }

    double mean1 = sum1 / (N / 2);
    double mean2 = sum2 / (N / 2);
    double mean = (mean1 + mean2) / 2.0;
    double error = std::abs(mean1 - mean2); // Error estimated via two sequences

    return {mean * V, error * V};
}

// --- Recursive Stratified Sampling ---
template<typename F, typename RNG>
MCResult stratmc(F f, std::vector<double> a, std::vector<double> b, int N, RNG& random_double, int nmin = 0) {
    int dim = a.size();
    if (nmin == 0) nmin = 10 * dim;

    if (N < nmin) {
	if (N<=0) N = 1;
        return plainmc(f, a, b, N, random_double);
    }

    std::vector<double> x(dim);
    std::vector<double> sum_left(dim, 0.0), sum_right(dim, 0.0);
    std::vector<double> sq_left(dim, 0.0), sq_right(dim, 0.0);
    std::vector<int> n_left(dim, 0), n_right(dim, 0);

    // Sample nmin points to estimate variances
    for (int i = 0; i < nmin; ++i) {
        for (int d = 0; d < dim; ++d) x[d] = a[d] + random_double() * (b[d] - a[d]);
        double fx = f(x);

        for (int d = 0; d < dim; ++d) {
            double mid = (a[d] + b[d]) / 2.0;
            if (x[d] < mid) {
                sum_left[d] += fx; sq_left[d] += fx * fx; n_left[d]++;
            } else {
                sum_right[d] += fx; sq_right[d] += fx * fx; n_right[d]++;
            }
        }
    }

    // Find dimension with largest sub-variance
    double max_var = -1.0;
    int split_dim = 0;
    std::vector<double> var_left(dim), var_right(dim);

    for (int d = 0; d < dim; ++d) {
        double vl = (n_left[d] > 0) ? (sq_left[d]/n_left[d] - std::pow(sum_left[d]/n_left[d], 2)) : 0;
        double vr = (n_right[d] > 0) ? (sq_right[d]/n_right[d] - std::pow(sum_right[d]/n_right[d], 2)) : 0;
        double sub_var = vl * n_left[d] + vr * n_right[d];
        var_left[d] = vl; var_right[d] = vr;

        if (sub_var > max_var) {
            max_var = sub_var;
            split_dim = d;
        }
    }

    // Divide remaining points proportional to sub-variances
    int N_rem = N - nmin;
    double var_L = var_left[split_dim];
    double var_R = var_right[split_dim];
    int N_left = N_rem / 2; // default safe fallback
    if (var_L + var_R > 0) {
        N_left = static_cast<int>(N_rem * var_L / (var_L + var_R));
    }
    int N_right = N_rem - N_left;

    // Dispatch recursive calls
    std::vector<double> a_right = a; a_right[split_dim] = (a[split_dim] + b[split_dim]) / 2.0;
    std::vector<double> b_left = b;  b_left[split_dim] = (a[split_dim] + b[split_dim]) / 2.0;

    MCResult res_left = stratmc(f, a, b_left, N_left, random_double, nmin);
    MCResult res_right = stratmc(f, a_right, b, N_right, random_double, nmin);

    return {res_left.value + res_right.value, std::sqrt(std::pow(res_left.error, 2) + std::pow(res_right.error, 2))};
}

} // namespace pp
