# Generated by Gemini 3
set terminal svg background rgb "white" size 800,600
set output "mc_results.svg"

set title "Monte Carlo Convergence Scaling" font ",16"
set xlabel "Number of points (N)"
set ylabel "Actual Absolute Error"
set logscale x 10
set logscale y 10
set format x "10^{%L}"
set format y "10^{%L}"
set grid
set key top right

plot "mc_scaling.txt" using 1:2 with linespoints pt 7 lw 2 lc rgb "red" title "Plain MC (LCG)", \
     "mc_scaling.txt" using 1:3 with linespoints pt 5 lw 2 lc rgb "blue" title "Quasi-Random (Halton)", \
     "mc_scaling.txt" using 1:4 with linespoints pt 9 lw 2 lc rgb "green" title "Stratified MC", \
     "mc_scaling.txt" using 1:5 with lines dt 2 lw 2 lc rgb "black" title "O(1/sqrt(N)) Reference"
